# Generated by Django 4.0 on 2022-01-05 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritesubject',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 1, 36, 43, 884762)),
        ),
    ]
