# Generated by Django 4.0 on 2022-01-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_favoritesubject_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesubject',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
