# Generated by Django 4.0 on 2022-01-05 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_favoritesubject_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesubject',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
